## 1. Introduction
 Sentiment analysis is a key Natural Language Processing (NLP) task that focuses on identifying the emotional tone behind textual data. It is widely used in applications such as product reviews, social media monitoring, recommendation systems, and customer feedback analysis.

This project aims to build a binary sentiment classification system that classifies movie reviews as positive or negative using classical NLP preprocessing techniques, TF‑IDF vectorization, and machine learning models.

The objective is not only to achieve high accuracy, but also to design an interpretable, efficient, and industry‑relevant NLP pipeline.

## 2. Dataset Description
The dataset consists of movie reviews with corresponding sentiment labels:
review: textual movie review
sentiment: binary label (0 = negative, 1 = positive)
The dataset contains 49,582 reviews, which were split into training and testing sets using a standard train‑test split to evaluate model generalization.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('IMDB Dataset.csv')

In [3]:
df['review'][10]

'Phil the Alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines.<br /><br />At first it was very odd and pretty funny but as the movie progressed I didn\'t find the jokes or oddness funny anymore.<br /><br />Its a low budget film (thats never a problem in itself), there were some pretty interesting characters, but eventually I just lost interest.<br /><br />I imagine this film would appeal to a stoner who is currently partaking.<br /><br />For something similar but better try "Brother from another planet"'

## Steps Involving the Text preprocessing
1. Text Preprocessing:-
Text preprocessing is a crucial step in NLP to reduce noise and improve model performance. The following preprocessing steps were applied sequentially:

2. Lowercasing:-
All text was converted to lowercase to ensure uniformity and avoid treating the same word differently due to case variations.

3. Removing URLs:- 
URLs were removed using regular expressions, as they do not contribute to sentiment information.

4. Removing Punctuation:-
All punctuation symbols were removed to retain only meaningful words.

5. Removing Extra Whitespaces:-
Multiple spaces were normalized into a single space to clean the text format.

6. Stopword Removal:-
Common English stopwords (e.g., the, is, and) were removed to reduce dimensionality and eliminate words with low semantic value.

In [4]:
df['review']=df.review.str.lower()

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df[df.duplicated(keep=False)].sample(5)

                                                  review sentiment
36975  first off, i just watched a movie on showtime ...  negative
39182  smallville episode justice is the best episode...  positive
29282  this movie starts off somewhat slowly and gets...  positive
31150  how has this piece of crap stayed on tv this l...  negative
26899  this is the final episode we deserved. at the ...  positive

In [7]:
df.duplicated(subset=['review']).sum()

np.int64(418)

In [8]:
df.duplicated(subset=['review','sentiment']).sum()

np.int64(418)

In [9]:
df.duplicated().sum()

np.int64(418)

In [10]:
print('Rows before:',len(df))
dup_count=df.duplicated(subset=['review']).sum()
print('Duplicated reviews (later occurrences):',dup_count)

Rows before: 50000
Duplicated reviews (later occurrences): 418

In [11]:
conflicts=(df.groupby('review')
          ['sentiment'].unique().sort_values(ascending=False))
print('Max unique labels per review:',conflicts.max())

Max unique labels per review: ['positive']

In [12]:
df=df.drop_duplicates(subset=['review'],keep='first').reset_index(drop=True)
print('Row after:',len(df))

Row after: 49582

In [13]:
print(df['sentiment'].value_counts())
print(df.isna().sum())

sentiment
positive    24884
negative    24698
Name: count, dtype: int64
review       0
sentiment    0
dtype: int64

In [14]:
df['review']=df['review'].fillna('')

In [15]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49577  i thought this movie did a down right good job...  positive
49578  bad plot, bad dialogue, bad acting, idiotic di...  negative
49579  i am a catholic taught in parochial elementary...  negative
49580  i'm going to have to disagree with the previou...  negative
49581  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [16]:
import re

In [17]:
def remove_html_tag(text):
    pattern=re.compile(r'<.*?>')
    return pattern.sub(' ',text).strip()

In [18]:
df['review']=df['review'].apply(remove_html_tag)

In [19]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production.   the filming t...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49577  i thought this movie did a down right good job...  positive
49578  bad plot, bad dialogue, bad acting, idiotic di...  negative
49579  i am a catholic taught in parochial elementary...  negative
49580  i'm going to have to disagree with the previou...  negative
49581  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [20]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.  this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.  ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.  3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [21]:
def removing_links(text):
    p=re.compile(r'https?://\S+|www\.\S+')
    return p.sub(r'',text)

In [22]:
df['review']=df['review'].apply(removing_links)

In [23]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production.   the filming t...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49577  i thought this movie did a down right good job...  positive
49578  bad plot, bad dialogue, bad acting, idiotic di...  negative
49579  i am a catholic taught in parochial elementary...  negative
49580  i'm going to have to disagree with the previou...  negative
49581  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [24]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
exclude=string.punctuation

In [26]:
def removing_punctuation(text):
    for i in exclude:
        text=text.replace(i,'')
    return text

In [27]:
df['review']=df['review'].apply(removing_punctuation)

In [28]:
df['review'][8]

'encouraged by the positive comments about this film on here i was looking forward to watching this film bad mistake ive seen 950 films and this is truly one of the worst of them  its awful in almost every way editing pacing storyline acting soundtrack the films only song  a lame country tune  is played no less than four times the film looks cheap and nasty and is boring in the extreme rarely have i been so happy to see the end credits of a film   the only thing that prevents me giving this a 1score is harvey keitel  while this is far from his best performance he at least seems to be making a bit of an effort one for keitel obsessives only'

In [29]:
def remove_extra_spaces(text):
    return re.sub(r'\s+',' ',text).strip()

In [30]:
df['review']=df['review'].apply(remove_extra_spaces)

In [31]:
def load_slang_dictionary(file_path):
    slang_dict = {}
    
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                slang_dict[key] = value
    
    return slang_dict

In [32]:
slang_dict = load_slang_dictionary("slang.txt")

In [33]:
slang_dict

{'A3': 'Anytime, Anywhere, Anyplace',
 'ADIH': 'Another Day In Hell',
 'AFK': 'Away From Keyboard',
 'AFAIK': 'As Far As I Know',
 'ASAP': 'As Soon As Possible',
 'ASL': 'Age, Sex, Location',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'BAE': 'Before Anyone Else',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRUH': 'Bro',
 'BRT': 'Be Right There',
 'BSAAW': 'Big Smile And A Wink',
 'BTW': 'By The Way',
 'BWL': 'Bursting With Laughter',
 'CSL': 'Can’t Stop Laughing',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'DM': 'Direct Message',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FIMH': 'Forever In My Heart',
 'FOMO': 'Fear Of Missing Out',
 'FR': 'For Real',
 'FWIW': "For What It's Worth",
 'FYP': 'For You Page',
 'FYI': 'For Your Information',
 'G9': 'Genius',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GMTA': 'Great Minds Think Alike',
 'GN': 'Good Night',
 'GOAT': 'Greatest Of All Time',
 'GR8': 'Great!',
 'HBD': 'Happy Birthday',
 'IC': 'I See',
 'ICQ': 'I Seek You',
 'IDC': 'I Don’t Care',
 'IDK': "I Don't Know",
 'IFYP': 'I Feel Your Pain',
 'ILU': 'I Love You',
 'ILY': 'I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMU': 'I Miss You',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'IYKYK': 'If You Know, You Know',
 'JK': 'Just Kidding',
 'KISS': 'Keep It Simple, Stupid',
 'L': 'Loss',
 'L8R': 'Later',
 'LDR': 'Long Distance Relationship',
 'LMK': 'Let Me Know',
 'LMAO': 'Laughing My A** Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'M8': 'Mate',
 'MFW': 'My Face When',
 'MID': 'Mediocre',
 'MRW': 'My Reaction When',
 'MTE': 'My Thoughts Exactly',
 'NVM': 'Never Mind',
 'NRN': 'No Reply Necessary',
 'NPC': 'Non-Player Character',
 'OIC': 'Oh I See',
 'OP': 'Overpowered',
 'PITA': 'Pain In The A**',
 'POV': 'Point Of View',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
 'RN': 'Right Now',
 'SK8': 'Skate',
 'STATS': 'Your Sex And Age',
 'SUS': 'Suspicious',
 'TBH': 'To Be Honest',
 'TFW': 'That Feeling When',
 'THX': 'Thank You',
 'TIME': 'Tears In My Eyes',
 'TLDR': 'Too Long, Didn’t Read',
 'TNTL': 'Trying Not To Laugh',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'W': 'Win',
 'W8': 'Wait...',
 'WB': 'Welcome Back',
 'WTF': 'What The F**k',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'WYD': 'What You Doing?',
 'WYWH': 'Wish You Were Here',
 'ZZZ': 'Sleeping, Bored, Tired'}

In [34]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in slang_dict:
            new_text.append(slang_dict[w.upper()])
        else:
            new_text.append(w)
    return ' '.join(new_text)

In [35]:
df['review']=df['review'].apply(chat_conversion)

In [36]:
df['review'][10]

'phil the alien is one of those quirky films where the humour is based around the oddness of everything rather than actual punchlines at first it was very odd and pretty funny but as the movie progressed i didnt find the jokes or oddness funny anymore its a low budget film thats never a problem in itself there were some pretty interesting characters but eventually i just lost interest i imagine this film would appeal to a stoner who is currently partaking for something similar but better try brother from another planet'

In [37]:
!pip install emoji

Requirement already satisfied: emoji in c:\users\user\anaconda3\lib\site-packages (2.15.0)

In [38]:
import emoji

In [39]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend Te...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the Tears In My Eyes of...  positive
...                                                  ...       ...
49577  i thought this movie did a down right good job...  positive
49578  bad plot bad dialogue bad acting idiotic direc...  negative
49579  i am a catholic taught in parochial elementary...  negative
49580  im going to have to disagree with the previous...  negative
49581  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [40]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\user\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\user\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.1.8)
Requirement already satisfied: joblib in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

from textblob import TextBlob

from textblob import TextBlob

df['polarity'] = df['review'].apply(
    lambda x: TextBlob(str(x)).sentiment.polarity
)

df['subjectivity'] = df['review'].apply(
    lambda x: TextBlob(str(x)).sentiment.subjectivity
)

In [41]:
import nltk

In [42]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [43]:
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords

In [44]:
stop_words =set(stopwords.words('english'))

In [45]:
words_imp = {
    "no", "not", "nor", "never", "cannot",
    "can't", "don't", "didn't", "isn't",
    "wasn't", "won't", "wouldn't",
    "couldn't", "shouldn't"
}

In [46]:
## Removing the stopswords except the words availabe in the words_imp
stop_words=stop_words-words_imp

In [47]:
df['review'] = df['review'].apply(lambda text : ' '.join([word for word in text.split() if word not in stop_words]))

def removing_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x=new_text[:]
    new_text.clear()
    return ' '.join(x)

df['review']=df['review'].apply(removing_stopwords)

In [48]:
## Checking the words stopwords are removed or not
df['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen not got polari voices pat truly see seamless editing guided references williams diary entries not well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

def tokenize_corpus(text):
    if text is None or pd.isna(text):
        return []
    if isinstance(text,pd.Series):
        return text.apply(tokenize_corpus)
    text=re.sub(r'[^a-zA-Z\s]','',text)
    return word_tokenize(text.lower())
df['review']=df['review'].apply(tokenize_corpus)
df['review'][1]

## Lemmatization

Lemmatization was applied using WordNetLemmatizer to convert words into their base forms (e.g., running → run, movies → movie). This helped reduce vocabulary size while preserving semantic meaning.
After preprocessing, the text was clean, normalized, and suitable for vectorization.

In [49]:
## Now applying the Lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [50]:
from nltk.stem import WordNetLemmatizer

In [51]:
lematizer=WordNetLemmatizer()

In [52]:
def lemmatize_text(text):
    return ' '.join([lematizer.lemmatize(word) for word in text.split()])

In [53]:
df['review']=df['review'].apply(lemmatize_text)

In [54]:
df['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion give comforting sometimes discomforting sense realism entire piece actor extremely well chosen michael sheen not got polari voice pat truly see seamless editing guided reference williams diary entry not well worth watching terrificly written performed piece masterful production one great master comedy life realism really come home little thing fantasy guard rather use traditional dream technique remains solid disappears play knowledge sens particularly scene concerning orton halliwell set particularly flat halliwells mural decorating every surface terribly well done'

## Applying encoding to the Sentiment feature

In [56]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['sentiment']=lb.fit_transform(df['sentiment'])

In [57]:
df.sentiment.unique()

array([1, 0])

In [58]:
x=df['review']
y=df['sentiment']

In [59]:
print(y.shape)
print(x.shape)

(49582,)
(49582,)

In [60]:
x

0        one reviewer mentioned watching 1 oz episode y...
1        wonderful little production filming technique ...
2        thought wonderful way spend Tears In My Eyes h...
3        basically there family little boy jake think t...
4        petter matteis love Tears In My Eyes money vis...
                               ...
49577    thought movie right good job wasnt creative or...
49578    bad plot bad dialogue bad acting idiotic direc...
49579    catholic taught parochial elementary school nu...
49580    im going disagree previous comment side maltin...
49581    no one expects star trek movie high art fan ex...
Name: review, Length: 49582, dtype: object

In [61]:
y.value_counts()

sentiment
1    24884
0    24698
Name: count, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

## Applying Bag-Of-words

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_bow=cv.fit_transform(x_train)
x_test_bow=cv.transform(x_test)

## **Applying the TF-IDF (Vectorization Technique)**

## Feature Extraction using TF-IDF

To convert textual movie reviews into numerical features suitable for machine learning models, TF-IDF (Term Frequency–Inverse Document Frequency) was used. TF-IDF helps represent text data in a way that highlights important words while reducing the influence of less meaningful terms.

### Why TF-IDF?

- Captures the importance of words relative to the entire corpus.
- Reduces the impact of frequently occurring but less informative words.
- Works extremely well with linear machine learning models.
- Efficient and scalable for large, sparse text datasets.

### Configuration

- The TF-IDF vectorizer was configured with the following parameters:

. max_features = 20000
. ngram_range = (1, 3)
. Unigrams (single words)
. Bigrams (two-word combinations)
. Trigrams (three-word combinations)

- This configuration allows the model to capture both individual word importance and short contextual phrases, which is particularly useful for     sentiment analysis.

**Final Feature Matrix Dimensions**

-After applying TF-IDF vectorization, the resulting feature matrices have the following dimensions:
- Training set: (39,665, 20,000)
- Test set: (9,917, 20,000)

. Each row represents a single movie review, and each column represents a TF-IDF feature extracted from the text corpus.

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=20000,ngram_range=(1,3))

In [64]:
x_train_tf=tfidf.fit_transform(x_train)
x_test_tf=tfidf.transform(x_test)

In [65]:
x_train_tf.shape
x_test_tf.shape

(9917, 20000)

In [66]:
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix

## Applying Logistic Regression

In [67]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(x_train_tf,y_train)

LogisticRegression()

### Training Accuracy

In [68]:
Y_pre_lg=lg.predict(x_train_tf)
print(classification_report(y_train,Y_pre_lg))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93     19775
           1       0.93      0.94      0.93     19890

    accuracy                           0.93     39665
   macro avg       0.93      0.93      0.93     39665
weighted avg       0.93      0.93      0.93     39665

In [69]:
Y_pred_lg=lg.predict(x_test_tf)
print(classification_report(y_test,Y_pred_lg))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      4923
           1       0.89      0.91      0.90      4994

    accuracy                           0.90      9917
   macro avg       0.90      0.90      0.90      9917
weighted avg       0.90      0.90      0.90      9917

In [70]:
print(accuracy_score(y_train,Y_pre_lg))
print(accuracy_score(y_test,Y_pred_lg))

0.9319299130215555
0.8972471513562569

In [ ]:
print(confusion_matrix(y_train,Y_pre_lg))
print(confusion_matrix(y_test,Y_pred_lg))

## SVM

In [71]:
from sklearn.svm import LinearSVC
svc=LinearSVC()
svc.fit(x_train_tf,y_train)

LinearSVC()

In [72]:
y_pre_svc=svc.predict(x_train_tf)
print(classification_report(y_train,y_pre_svc))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98     19775
           1       0.98      0.98      0.98     19890

    accuracy                           0.98     39665
   macro avg       0.98      0.98      0.98     39665
weighted avg       0.98      0.98      0.98     39665

In [73]:
y_pred_svc=svc.predict(x_test_tf)
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90      4923
           1       0.89      0.91      0.90      4994

    accuracy                           0.90      9917
   macro avg       0.90      0.90      0.90      9917
weighted avg       0.90      0.90      0.90      9917

## Applying Multinomial Navie-bias

In [74]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train_tf,y_train)

MultinomialNB()

## Testing Accuracy of the Multinomial navie bias

In [75]:
y_pred_mnb=mnb.predict(x_train_tf)
print(classification_report(y_pred_mnb,y_train))

              precision    recall  f1-score   support

           0       0.88      0.91      0.90     19253
           1       0.91      0.89      0.90     20412

    accuracy                           0.90     39665
   macro avg       0.90      0.90      0.90     39665
weighted avg       0.90      0.90      0.90     39665

## Training Accuracy Of Navie bias

In [76]:
y_predict_mng=mnb.predict(x_test_tf)
print(classification_report(y_predict_mng,y_test))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87      4781
           1       0.89      0.86      0.88      5136

    accuracy                           0.87      9917
   macro avg       0.87      0.87      0.87      9917
weighted avg       0.87      0.87      0.87      9917

# Machine Learning Models

1 Logistic Regression
- Used as a baseline linear model for text classification
- Train accuracy: 93%
- Test accuracy: 90%
- Precision and recall are balanced for both classes
- Shows good generalization with minimal overfitting

2. Support Vector Machine (LinearSVC)
- Linear SVM works well with high-dimensional sparse TF-IDF features
- Train accuracy: 98%
- Test accuracy: 90%
- F1-score: 0.90 for both classes
- Best balance between performance and generalization

# Model Evaluation
1. **Evaluation metrics used**:
- Accuracy
-Precision
- Recall
- F1-score
- Confusion Matrix

-- Confusion matrix shows low misclassification.
-- No major class bias observed.

## Model Comparison
1. **Logistic Regression** -> Test accuracy: 90%, simple and interpretable
2. **Linear SVM** -> Test accuracy: 90%, strong on sparse text data
- Linear SVM selected as final model due to better robustness

# Why Ensemble Methods Were Not Used

**Ensemble methods such as Random Forest or XGBoost were intentionally avoided because**:

- They do not scale well on sparse TF‑IDF matrices
- Linear models outperform ensembles in text classification tasks

-->Increased complexity without meaningful performance gain.This decision aligns with industry best practices for NLP.

# Conclusion

-This project successfully implemented an end‑to‑end sentiment analysis pipeline using classical NLP and machine learning techniques. The combination of TF‑IDF vectorization with Linear SVM achieved strong and reliable performance.

**Key Takeaways**:

- Proper preprocessing significantly improves results
- TF‑IDF remains a powerful feature extraction technique
- Linear models are highly effective for text classification
- Model simplicity leads to better interpretability and stability


**The final model achieved 90% test accuracy, making it suitable for real‑world sentiment analysis applications.**